"""add_fk_indexes

Revision ID: 013771a9e13b
Revises: e35c547f0798
Create Date: 2026-06-29 12:40:57.298846

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "013771a9e13b"
down_revision: str | Sequence[str] | None = "e35c547f0798"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_document_pages_document_id"),
        "document_pages",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_project_id"), "documents", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_draft_responses_requirement_id"),
        "draft_responses",
        ["requirement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirements_project_id"), "requirements", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_requirements_source_document_id"),
        "requirements",
        ["source_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requirements_source_document_id"), table_name="requirements")
    op.drop_index(op.f("ix_requirements_project_id"), table_name="requirements")
    op.drop_index(
        op.f("ix_draft_responses_requirement_id"), table_name="draft_responses"
    )
    op.drop_index(op.f("ix_documents_project_id"), table_name="documents")
    op.drop_index(op.f("ix_document_pages_document_id"), table_name="document_pages")
    # ### end Alembic commands ###
