"""add_processing_error_to_document

Revision ID: 143119456f57
Revises: 013771a9e13b
Create Date: 2026-06-29 12:45:10.746344

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "143119456f57"
down_revision: str | Sequence[str] | None = "013771a9e13b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("processing_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "processing_error")
    # ### end Alembic commands ###
