"""add_request_id_to_audit_events

Revision ID: 35bf60412d49
Revises: f0093fb3f942
Create Date: 2026-07-08 15:08:17.929533

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35bf60412d49"
down_revision: str | Sequence[str] | None = "f0093fb3f942"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_events", sa.Column("request_id", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_events", "request_id")
    # ### end Alembic commands ###
