"""update_document_slice4

Revision ID: 950eb46a82b7
Revises: 966c2d5c6d72
Create Date: 2026-06-26 11:51:13.328718

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "950eb46a82b7"
down_revision: str | Sequence[str] | None = "966c2d5c6d72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("owner_name", sa.String(length=255), nullable=True)
    )
    op.add_column("documents", sa.Column("tags", sa.Text(), nullable=True))
    op.add_column(
        "documents",
        sa.Column(
            "approval_status",
            sa.String(length=50),
            nullable=False,
            server_default="PENDING",
        ),
    )
    op.add_column(
        "documents", sa.Column("version", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("review_date", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "review_date")
    op.drop_column("documents", "version")
    op.drop_column("documents", "approval_status")
    op.drop_column("documents", "tags")
    op.drop_column("documents", "owner_name")
    # ### end Alembic commands ###
