"""update_requirement_slice3

Revision ID: 966c2d5c6d72
Revises: f37193ec5195
Create Date: 2026-06-26 11:47:46.102342

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "966c2d5c6d72"
down_revision: str | Sequence[str] | None = "f37193ec5195"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("requirements", sa.Column("original_text", sa.Text(), nullable=False))
    op.add_column(
        "requirements",
        sa.Column("source_section", sa.String(length=100), nullable=True),
    )
    op.add_column("requirements", sa.Column("source_page", sa.Integer(), nullable=True))
    op.add_column(
        "requirements",
        sa.Column("requirement_type", sa.String(length=100), nullable=True),
    )
    op.add_column("requirements", sa.Column("mandatory", sa.Boolean(), nullable=False))
    op.add_column(
        "requirements", sa.Column("owner_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "requirements",
        sa.Column("proposal_section", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "requirements", sa.Column("risk_level", sa.String(length=50), nullable=True)
    )
    op.drop_column("requirements", "identifier")
    op.drop_column("requirements", "text")
    op.drop_column("requirements", "page_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requirements",
        sa.Column("page_number", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "requirements",
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "identifier", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("requirements", "risk_level")
    op.drop_column("requirements", "proposal_section")
    op.drop_column("requirements", "owner_name")
    op.drop_column("requirements", "mandatory")
    op.drop_column("requirements", "requirement_type")
    op.drop_column("requirements", "source_page")
    op.drop_column("requirements", "source_section")
    op.drop_column("requirements", "original_text")
    # ### end Alembic commands ###
