"""update_draft_response_slice5

Revision ID: ba7653529c7f
Revises: 950eb46a82b7
Create Date: 2026-06-26 11:56:04.208917

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba7653529c7f"
down_revision: str | Sequence[str] | None = "950eb46a82b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "draft_responses", sa.Column("confidence", sa.Float(), nullable=False)
    )
    op.add_column(
        "draft_responses", sa.Column("needs_evidence", sa.Boolean(), nullable=False)
    )
    op.add_column("draft_responses", sa.Column("assumptions", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("draft_responses", "assumptions")
    op.drop_column("draft_responses", "needs_evidence")
    op.drop_column("draft_responses", "confidence")
    # ### end Alembic commands ###
