"""add_request_id_to_processing_jobs

Revision ID: ce1d99d00aeb
Revises: 35bf60412d49
Create Date: 2026-07-08 15:09:03.023433

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce1d99d00aeb"
down_revision: str | Sequence[str] | None = "35bf60412d49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_jobs", sa.Column("request_id", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_jobs", "request_id")
    # ### end Alembic commands ###
