"""remove_unique_constraint_and_add_version

Revision ID: e35c547f0798
Revises: ba7653529c7f
Create Date: 2026-06-29 12:39:06.336575

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e35c547f0798"
down_revision: str | Sequence[str] | None = "ba7653529c7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "draft_responses",
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_constraint(
        op.f("draft_responses_requirement_id_key"), "draft_responses", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("draft_responses_requirement_id_key"),
        "draft_responses",
        ["requirement_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("draft_responses", "version")
    # ### end Alembic commands ###
