"""add_reviewer_assignment_and_comments

Revision ID: ef0310e3c06f
Revises: 143119456f57
Create Date: 2026-07-08 14:42:12.717889

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef0310e3c06f"
down_revision: str | Sequence[str] | None = "143119456f57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirement_comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("decision_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["requirement_id"], ["requirements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirement_comments_author_user_id"),
        "requirement_comments",
        ["author_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_comments_requirement_id"),
        "requirement_comments",
        ["requirement_id"],
        unique=False,
    )
    op.add_column(
        "requirements", sa.Column("assigned_to_user_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "requirements", sa.Column("assigned_by_user_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "requirements",
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_requirements_assigned_by_user_id"),
        "requirements",
        ["assigned_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirements_assigned_to_user_id"),
        "requirements",
        ["assigned_to_user_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "requirements",
        "users",
        ["assigned_to_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "requirements",
        "users",
        ["assigned_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requirements", type_="foreignkey")
    op.drop_constraint(None, "requirements", type_="foreignkey")
    op.drop_index(
        op.f("ix_requirements_assigned_to_user_id"), table_name="requirements"
    )
    op.drop_index(
        op.f("ix_requirements_assigned_by_user_id"), table_name="requirements"
    )
    op.drop_column("requirements", "assigned_at")
    op.drop_column("requirements", "assigned_by_user_id")
    op.drop_column("requirements", "assigned_to_user_id")
    op.drop_index(
        op.f("ix_requirement_comments_requirement_id"),
        table_name="requirement_comments",
    )
    op.drop_index(
        op.f("ix_requirement_comments_author_user_id"),
        table_name="requirement_comments",
    )
    op.drop_table("requirement_comments")
    # ### end Alembic commands ###
