"""Fixed-behavior counterparts to test_a3_production_config_weaknesses.py,
plus the Compose-structural checks from spec section 12 ("Compose",
items 32-37). These assert the CURRENT (fixed) state of the repository.

Compose-rendering tests shell out to `docker compose config` and are
skipped if the Docker CLI is unavailable -- they need local secret files
generated by scripts/generate_local_prod_secrets.py, which they generate
into a throwaway temp copy of the secrets directory structure via the
`COMPOSE_PROJECT_DIR`-independent `secrets/` path relative to the repo, so
they do not depend on (or clobber) any secrets/ the developer already has.
"""

import json
import pathlib
import shutil
import subprocess

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]


def _read(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def _docker_available() -> bool:
    return shutil.which("docker") is not None


# ---------------------------------------------------------------------------
# Fixed-behavior counterparts (static file content)
# ---------------------------------------------------------------------------


def test_fix_1_no_fixed_postgres_password_in_prod_compose():
    compose = _read("docker-compose.prod.yml")
    assert "rfp_password" not in compose


def test_fix_2_no_plain_env_var_secrets_in_prod_compose():
    compose = _read("docker-compose.prod.yml")
    assert "SESSION_SECRET_KEY=${SESSION_SECRET_KEY}" not in compose
    assert "secrets:" in compose
    for secret_name in (
        "app_secret",
        "session_secret",
        "throttle_secret",
        "postgres_password",
        "redis_password",
        "anthropic_api_key",
    ):
        assert secret_name in compose


def test_fix_3_prod_compose_selects_anthropic_provider():
    compose = _read("docker-compose.prod.yml")
    assert "LLM_PROVIDER: anthropic" in compose
    assert "LLM_PROVIDER=fake" not in compose
    assert "LLM_MODEL" in compose


def test_fix_4_prod_compose_includes_login_throttle_secret():
    compose = _read("docker-compose.prod.yml")
    assert "throttle_secret" in compose
    assert "LOGIN_THROTTLE_SECRET_FILE" in compose


def test_fix_5_app_bound_to_loopback_only():
    compose = _read("docker-compose.prod.yml")
    assert "127.0.0.1:8000:8000" in compose
    assert '"8000:8000"' not in compose


def test_fix_6_persistent_document_storage_volume_present():
    compose = _read("docker-compose.prod.yml")
    assert "app_storage" in compose
    assert "/data/storage" in compose


def test_fix_7_staging_docs_no_longer_advertise_openai():
    staging_env = _read(".env.staging.example")
    # No OPENAI_* configuration variable exists (the word "openai" may
    # still appear in prose explaining that it isn't supported).
    assert "OPENAI_API_KEY" not in staging_env
    assert "LLM_PROVIDER=anthropic" in staging_env


def test_fix_8_deployment_docs_no_longer_use_malformed_password_hash():
    deployment_doc = _read("DEPLOYMENT.md")
    # The executable user-creation snippet now hashes a real placeholder
    # password rather than assigning the literal string "not-applicable"
    # (prose elsewhere may still reference the old string as a warning).
    assert "hashed_password=hash_password(" in deployment_doc
    assert "set_user_password.py" in deployment_doc


# ---------------------------------------------------------------------------
# Compose structural checks (require Docker CLI; skipped otherwise)
# ---------------------------------------------------------------------------

pytestmark_docker = pytest.mark.skipif(
    not _docker_available(), reason="Docker CLI not available"
)


@pytest.fixture(scope="module")
def rendered_compose_config():
    if not _docker_available():
        pytest.skip("Docker CLI not available")

    secrets_dir = REPO_ROOT / "secrets"
    created_files = []
    secrets_dir.mkdir(exist_ok=True)
    required_files = {
        "app_secret.txt": "test-app-secret-32-chars-minimum-xx",
        "session_secret.txt": "test-session-secret-32-chars-minimum",
        "throttle_secret.txt": "test-throttle-secret-32-chars-minimum",
        "postgres_password.txt": "test-postgres-password",
        "redis_password.txt": "test-redis-password",
        "redis.conf": "requirepass test-redis-password\nappendonly yes\n",
        "anthropic_api_key.txt": "sk-ant-test-key-not-real",
    }
    for name, content in required_files.items():
        path = secrets_dir / name
        if not path.exists():
            path.write_text(content + "\n", encoding="utf-8")
            created_files.append(path)

    try:
        result = subprocess.run(
            [
                "docker",
                "compose",
                "-f",
                "docker-compose.prod.yml",
                "config",
                "--format",
                "json",
            ],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert result.returncode == 0, result.stderr
        yield json.loads(result.stdout)
    finally:
        for path in created_files:
            path.unlink(missing_ok=True)


@pytestmark_docker
def test_compose_config_renders_successfully(rendered_compose_config):
    assert "services" in rendered_compose_config


@pytestmark_docker
def test_compose_contains_no_fixed_credential(rendered_compose_config):
    rendered_text = json.dumps(rendered_compose_config)
    assert "rfp_password" not in rendered_text


@pytestmark_docker
def test_compose_app_is_loopback_bound_only(rendered_compose_config):
    app_ports = rendered_compose_config["services"]["app"]["ports"]
    assert len(app_ports) == 1
    assert app_ports[0]["host_ip"] == "127.0.0.1"


@pytestmark_docker
def test_compose_worker_has_no_published_port(rendered_compose_config):
    worker = rendered_compose_config["services"]["worker"]
    assert "ports" not in worker or not worker["ports"]


@pytestmark_docker
def test_compose_postgres_and_redis_are_private(rendered_compose_config):
    for svc_name in ("postgres", "redis"):
        svc = rendered_compose_config["services"][svc_name]
        assert "ports" not in svc or not svc["ports"]


@pytestmark_docker
def test_compose_only_required_secrets_mounted_per_service(rendered_compose_config):
    services = rendered_compose_config["services"]

    def secret_sources(service_name: str) -> set[str]:
        return {s["source"] for s in services[service_name].get("secrets", [])}

    assert secret_sources("postgres") == {"postgres_password"}
    assert secret_sources("redis") == {"redis_conf", "redis_password"}
    app_secrets = secret_sources("app")
    assert app_secrets == {
        "app_secret",
        "session_secret",
        "throttle_secret",
        "postgres_password",
        "redis_password",
        "anthropic_api_key",
    }
