# scripts/generate_local_prod_secrets.py
# Generates LOCAL VALIDATION credentials for docker-compose.prod.yml.
#
# These are NOT production credentials. They exist purely so an operator
# can run the production-like Compose stack on a laptop/CI runner to
# validate configuration, without ever inventing or committing a real
# secret.
#
# Usage:
#   uv run python scripts/generate_local_prod_secrets.py
#   uv run python scripts/generate_local_prod_secrets.py --force
#   uv run python scripts/generate_local_prod_secrets.py --import-anthropic-key
#   uv run python scripts/generate_local_prod_secrets.py --cleanup
#
# Never accepts secret VALUES as command-line arguments and never prints
# any generated value.

import argparse
import os
import secrets as secrets_module
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

SECRETS_DIR = "secrets"

# Filenames this script owns. `redis.conf` is derived from redis_password
# and also lives here; cleanup only ever touches files in this list plus
# the redis.conf it generated, and only inside SECRETS_DIR.
_GENERATED_TOKEN_FILES = {
    "app_secret.txt": 32,
    "session_secret.txt": 32,
    "throttle_secret.txt": 32,
    "postgres_password.txt": 24,
    "redis_password.txt": 24,
}
_DERIVED_FILES = ("redis.conf",)
_MANUAL_FILES = ("anthropic_api_key.txt",)

_LABEL_HEADER = (
    "# LOCAL VALIDATION CREDENTIAL -- generated by "
    "scripts/generate_local_prod_secrets.py. NOT a production credential.\n"
)


def _secrets_dir_path() -> str:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(repo_root, SECRETS_DIR)


def _write_secret_file(path: str, value: str, *, force: bool) -> bool:
    if os.path.exists(path) and not force:
        print(f"SKIP (exists, use --force to overwrite): {os.path.basename(path)}")
        return False

    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(value + "\n")

    try:
        # World-readable rather than 0600: these are local-validation-only
        # credentials (explicitly documented as such, never real production
        # secrets), and Docker Compose bind-mounts secret files preserving
        # the HOST file's mode -- app/worker/postgres/redis each run as
        # their own non-root, non-matching container uid, so an
        # owner-only-readable file would be unreadable inside the
        # container regardless of which host user generated it.
        os.chmod(path, 0o644)  # no-op on platforms without POSIX permissions
    except OSError:
        pass

    print(f"Wrote: {os.path.basename(path)}")
    return True


def _generate_token(n_bytes: int) -> str:
    return secrets_module.token_urlsafe(n_bytes)


def cmd_generate(force: bool, import_anthropic_key: bool) -> int:
    secrets_dir = _secrets_dir_path()
    os.makedirs(secrets_dir, exist_ok=True)
    try:
        os.chmod(secrets_dir, 0o700)
    except OSError:
        pass

    generated_values: dict[str, str] = {}
    for filename, n_bytes in _GENERATED_TOKEN_FILES.items():
        path = os.path.join(secrets_dir, filename)
        value = _generate_token(n_bytes)
        if _write_secret_file(path, value, force=force):
            generated_values[filename] = value
        elif os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                generated_values[filename] = f.read().strip()

    redis_password = generated_values.get("redis_password.txt")
    if redis_password:
        redis_conf_path = os.path.join(secrets_dir, "redis.conf")
        redis_conf_body = (
            _LABEL_HEADER + f"requirepass {redis_password}\nappendonly yes\n"
        )
        _write_secret_file(redis_conf_path, redis_conf_body.rstrip("\n"), force=force)

    anthropic_path = os.path.join(secrets_dir, "anthropic_api_key.txt")
    if import_anthropic_key:
        if os.path.exists(anthropic_path) and not force:
            print("SKIP (exists, use --force to overwrite): anthropic_api_key.txt")
        else:
            env_var_value = os.environ.get("ANTHROPIC_API_KEY_IMPORT")
            if env_var_value:
                key_value = env_var_value
                print("Importing Anthropic key from ANTHROPIC_API_KEY_IMPORT env var.")
            else:
                from getpass import getpass

                key_value = getpass("Anthropic API key (input hidden): ")
            if not key_value.strip():
                print("ERROR: empty Anthropic API key; not writing a file.")
                return 1
            _write_secret_file(anthropic_path, key_value.strip(), force=force)
    elif not os.path.exists(anthropic_path):
        print(
            "NOTE: secrets/anthropic_api_key.txt was not created. This "
            "script never generates or invents an Anthropic key. Re-run "
            "with --import-anthropic-key to provide one interactively, or "
            "create the file yourself before starting the stack."
        )

    print(
        "\nAll values above are LOCAL VALIDATION credentials only -- "
        "never use them for a real deployment."
    )
    return 0


def cmd_cleanup() -> int:
    secrets_dir = _secrets_dir_path()
    if not os.path.isdir(secrets_dir):
        print("Nothing to clean up: secrets/ does not exist.")
        return 0

    candidates = [
        os.path.join(secrets_dir, name)
        for name in (
            *_GENERATED_TOKEN_FILES.keys(),
            *_DERIVED_FILES,
            *_MANUAL_FILES,
        )
    ]
    existing = [p for p in candidates if os.path.isfile(p)]
    if not existing:
        print("Nothing to clean up: no generated secret files found.")
        return 0

    print("The following files will be permanently deleted:")
    for p in existing:
        print(f"  - {p}")
    answer = input("Confirm deletion? [y/N]: ").strip().lower()
    if answer not in ("y", "yes"):
        print("Aborted; no files were deleted.")
        return 1

    for p in existing:
        os.remove(p)
        print(f"Deleted: {os.path.basename(p)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate LOCAL VALIDATION secrets for docker-compose.prod.yml. "
            "Never use the output for a real deployment."
        )
    )
    parser.add_argument(
        "--force", action="store_true", help="Overwrite existing secret files."
    )
    parser.add_argument(
        "--import-anthropic-key",
        action="store_true",
        help=(
            "Interactively import an Anthropic API key via getpass (or from "
            "the ANTHROPIC_API_KEY_IMPORT environment variable if set). "
            "Never generated -- always operator-supplied."
        ),
    )
    parser.add_argument(
        "--cleanup",
        action="store_true",
        help="Remove only the files this script generated, after confirmation.",
    )
    args = parser.parse_args()

    if args.cleanup:
        return cmd_cleanup()
    return cmd_generate(
        force=args.force, import_anthropic_key=args.import_anthropic_key
    )


if __name__ == "__main__":
    sys.exit(main())
